trace-entry-pipeline:
  workers: 2
  source:
    otel_trace_source:
      port: 21890
      ssl: true
      sslKeyCertChainFile: "{{ DATA_PREPPER_TLS_CERTIFICATE }}"
      sslKeyFile: "{{ DATA_PREPPER_TLS_PRIVATE_KEY }}"
      health_check_service: true
  buffer:
    bounded_blocking:
      buffer_size: 4096
      batch_size: 64
  sink:
    - pipeline:
        name: trace-raw-pipeline
    - pipeline:
        name: trace-service-map-pipeline

trace-raw-pipeline:
  workers: 2
  source:
    pipeline:
      name: trace-entry-pipeline
  processor:
    - otel_traces:
  sink:
    - opensearch:
        hosts: ["{{ OPENSEARCH_HTTPS_ENDPOINT }}"]
        username: "{{ OPENSEARCH_INGEST_USERNAME }}"
        password: "{{ OPENSEARCH_INGEST_PASSWORD }}"
        cert: "{{ OPENSEARCH_CA_CERTIFICATE }}"
        index_type: trace-analytics-raw

trace-service-map-pipeline:
  workers: 1
  source:
    pipeline:
      name: trace-entry-pipeline
  buffer:
    bounded_blocking:
      buffer_size: 2048
      batch_size: 32
  processor:
    - otel_apm_service_map:
        window_duration: 60s
        db_path: /var/lib/data-prepper/otel-apm-service-map
  route:
    - otel_apm_service_map_route: 'getEventType() == "SERVICE_MAP"'
  sink:
    - opensearch:
        hosts: ["{{ OPENSEARCH_HTTPS_ENDPOINT }}"]
        username: "{{ OPENSEARCH_INGEST_USERNAME }}"
        password: "{{ OPENSEARCH_INGEST_PASSWORD }}"
        cert: "{{ OPENSEARCH_CA_CERTIFICATE }}"
        index_type: otel-v2-apm-service-map
        routes: [otel_apm_service_map_route]

log-pipeline:
  workers: 2
  source:
    otel_logs_source:
      port: 21891
      ssl: true
      sslKeyCertChainFile: "{{ DATA_PREPPER_TLS_CERTIFICATE }}"
      sslKeyFile: "{{ DATA_PREPPER_TLS_PRIVATE_KEY }}"
      health_check_service: true
  buffer:
    bounded_blocking:
      buffer_size: 4096
      batch_size: 64
  sink:
    - opensearch:
        hosts: ["{{ OPENSEARCH_HTTPS_ENDPOINT }}"]
        username: "{{ OPENSEARCH_INGEST_USERNAME }}"
        password: "{{ OPENSEARCH_INGEST_PASSWORD }}"
        cert: "{{ OPENSEARCH_CA_CERTIFICATE }}"
        index_type: custom
        index: otel-logs-%{yyyy.MM.dd}
